-- 1. Show the top 5 customers with the highest total cost of orders.

SELECT c.customer_name, SUM(cart.total_cost) AS total_cost
FROM customer c
JOIN cart on cart.customer_id=c.customer_id
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_cost DESC
LIMIT 5;

-- 2. Show the top categories with the highest total revenue.

SELECT c.catregory_name, SUM(o.total_cost) AS total_revenue
FROM category c
JOIN product p ON c.category_id = p.category_id
JOIN orders o ON p.product_id = o.cart_id
GROUP BY c.catregory_name
ORDER BY total_revenue DESC
LIMIT 5;


-- 3. Show the total number of orders and total revenue generated by each retailer in the last month.

SELECT r.retailer_id, COUNT(o.order_id) AS total_orders, SUM(o.total_cost) AS total_revenue
FROM retailer r
JOIN product p ON r.retailer_id = p.retailer_id
JOIN orders o ON p.product_id = o.cart_id
WHERE o.time_date >= DATE_SUB(NOW(), INTERVAL 1 MONTH)
GROUP BY r.retailer_id;

-- 4. Show the average order cost for each retailer.

SELECT r.retailer_id, AVG(o.total_cost) AS average_order_cost
FROM retailer r
JOIN product p ON r.retailer_id = p.retailer_id
JOIN orders o ON p.product_id = o.cart_id
GROUP BY r.retailer_id;

-- 5. Show the average age of customers who placed orders in the last 3 months.

SELECT AVG(c.customer_age) AS average_age
FROM customer c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.time_date >= DATE_SUB(NOW(), INTERVAL 3 MONTH);

-- 6. Show the total revenue generated by each delivery partner type.
SELECT dp.type, SUM(o.total_cost) AS total_revenue
FROM delivery_partner dp
JOIN orders o ON dp.delivery_partner_id = o.delivery_partner_id
GROUP BY dp.type;


-- 7. Show the total number of orders and total revenue generated by each retailer in the last month.

SELECT r.retailer_id, COUNT(o.order_id) AS total_orders, SUM(o.total_cost) AS total_revenue
FROM retailer r
JOIN product p ON r.retailer_id = p.retailer_id
JOIN orders o ON p.product_id = o.cart_id
WHERE o.time_date >= DATE_SUB(NOW(), INTERVAL 1 MONTH)
GROUP BY r.retailer_id;
